# Change the default prompt format
format = """\
[╭╴](238)\
$env_var\
[](fg:#1d2230)\
$username\
[](bg:#3B76F0 fg:#1d2230)\
$directory\
[](fg:#3B76F0 bg:#86BBD8)\
[](bg:#06969A fg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#06969A bg:#86BBD8)\
[](fg:#86BBD8 bg:#3B76F0)\
$docker_context\
[](fg:#3B76F0)
$fill\
$package\
$php\
$python\
$nodejs\
[](fg:#86BBD8)\ 
$status\
[](bg:#86BBD8 fg:blue)\ 
$cmd_duration\
[](fg:#1d2230 bg:blue)\ 
$time\
[](fg:#1d2230)\
\n[╰─](238)$character"""

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Change the default prompt characters
[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:blue"

[directory]
style = "fg:#E4E4E4 bg:#3B76F0"
format = "[$path]($style)[$read_only]($read_only_style)"
read_only_style = "197"
read_only = " 🔒 "
truncation_length = 8
truncation_symbol = '…/'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Desktop" = ""
"Projects" = ""

[docker_context]
format = "via [🐳 $context](bold blue) "

[fill]
symbol = ' '

[git_branch]
symbol = "🌱"
truncation_length = 4
truncation_symbol = ""
style = "bg:#FCA17D"
format = 'on [[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bg:#FCA17D"    
conflicted = "🏳"
up_to_date = " "
untracked = "🤷"
ahead = "🏎️💨⇡${count}"
diverged = "🏎️💨⇕⇡${ahead_count} 🐢⇣${behind_count}"
behind = "🐢⇣${count}"
stashed = "📦 "
modified = "📝"
staged = '[🗃️+\($count\)](green)'
renamed = "📛"
deleted = "🗑️"

#[kubernetes]
#format = 'on [$context\($namespace\)](bold purple) '
#disabled = false
#[kubernetes.context_aliases]
#"clcreative-k8s-staging" = "cl-k8s-staging"
#"clcreative-k8s-production" = "cl-k8s-prod"

[nodejs]
symbol = "🤖"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#format = 'via [🤖 $version](bold green) '

[package]
format = 'via [🎁 $version](208 bold) '

[php]
symbol = "🐘"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#format = 'via [🔹 $version](147 bold) '

[python]
symbol = "🐍 "
python_binary = "python3"

[status]
style = 'bg:#86BBD8'
symbol = '❌ '
success_symbol = '✓ '
not_found_symbol = '🔍 '
sigint_symbol = '🧱 '
format = '[ \[$symbol$common_meaning$signal_name$maybe_int\]]($style)'
map_symbol = true
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#3B76F0 bg:#1d2230"
format = '[ 🕙 $time ]($style)'

[username]
style_user = "fg:#3B76F0 bg:#1d2230"
style_root = 'black bold'
format = '[ $user]($style) '
disabled = false
show_always = true
